import { z } from "zod";

import { RequestId } from "./common.js";

export const ErrorCode = z.enum([
  "AUTH_REQUIRED",
  "AUTH_INVALID_CREDENTIALS",
  "AUTH_TOKEN_EXPIRED",
  "AUTH_TOKEN_REVOKED",
  "DEVICE_REVOKED",
  "ACCOUNT_EXISTS",
  "VERIFICATION_INVALID",
  "VERIFICATION_EXPIRED",
  "VERIFICATION_RATE_LIMITED",
  "PASSWORD_RESET_FAILED",
  "ORG_FORBIDDEN",
  "ORG_NOT_FOUND",
  "CAPABILITY_NOT_FOUND",
  "IDEMPOTENCY_CONFLICT",
  "RATE_LIMITED",
  "PHONE_PROVIDER_UNAVAILABLE",
  "SPACE_NOT_FOUND",
  "SPACE_FORBIDDEN",
  "SPACE_READONLY",
  "QUOTA_EXCEEDED",
  "FILE_NOT_FOUND",
  "FILE_FORBIDDEN",
  "FILE_NAME_CONFLICT",
  "FILE_VERSION_CONFLICT",
  "UPLOAD_NOT_FOUND",
  "UPLOAD_EXPIRED",
  "UPLOAD_INCOMPLETE",
  "UPLOAD_CHECKSUM_MISMATCH",
  "FOLDER_MANAGER_REQUIRED",
  "FOLDER_LAST_MANAGER",
  "WORK_NOT_FOUND",
  "WORK_FORBIDDEN",
  "WORK_VERSION_CONFLICT",
  "WORK_TRANSITION_INVALID",
  "ASSIGNMENT_NOT_FOUND",
  "PROCESS_NOT_FOUND",
  "PROCESS_FORBIDDEN",
  "PROCESS_VERSION_CONFLICT",
  "PROCESS_TRANSITION_INVALID",
  "OKR_NOT_FOUND",
  "OKR_FORBIDDEN",
  "OKR_VERSION_CONFLICT",
  "PARTNER_NOT_FOUND",
  "PARTNER_FORBIDDEN",
  "PARTNER_VERSION_CONFLICT",
  "NOTIFICATION_NOT_FOUND",
  "NOTIFICATION_FORBIDDEN",
  "NOTIFICATION_VERSION_CONFLICT",
  "VALIDATION_FAILED",
  "INTERNAL_ERROR",
]);
export type ErrorCode = z.infer<typeof ErrorCode>;

export const ErrorEnvelope = z
  .object({
    error: z
      .object({
        code: ErrorCode,
        message: z.string().min(1),
        requestId: RequestId,
        details: z.record(z.string(), z.unknown()).optional(),
      })
      .strict(),
  })
  .strict();
export type ErrorEnvelope = z.infer<typeof ErrorEnvelope>;
