export const GIBIBYTE = 1024n ** 3n;
export const DEFAULT_PERSONAL_QUOTA_BYTES = 50n * GIBIBYTE;
export const MAX_PERSONAL_QUOTA_BYTES = 500n * GIBIBYTE;
export const ORGANIZATION_QUOTA_BYTES = 500n * GIBIBYTE;
